### ISSUE TITLE
UB-Mannheim/AustrianNewspapers

### ISSUE THREAD

**Issue by kba** [cneud/ocr-gt#15]
https://github.com/UB-Mannheim/AustrianNewspapers

**Comment by stweil** [comment]
`ONB_NewsEye` is already registered in `ocr-gt.yml`. `UB-Mannheim/AustrianNewspapers` is based on that data set, but contains fixed and enhanced GT.

**Comment by cneud** [comment]
Yes, I think it would be best to have two separate entries for this.
